"""Updated: reminder to recurrence using RRULE

Revision ID: 2e6b81620118
Revises: 82b403455c40
Create Date: 2025-12-29 19:10:18.670019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e6b81620118'
down_revision = '82b403455c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.JSON(), nullable=True))
        batch_op.drop_column('reminder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder', postgresql.ENUM('None', 'Weekly', 'Monthly', 'Yearly', name='reminder_type'), autoincrement=False, nullable=True))
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
