"""Modified: allergies to description for sheets

Revision ID: 506d82877fff
Revises: 2251bb233460
Create Date: 2025-12-31 23:50:36.263393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506d82877fff'
down_revision = '2251bb233460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('allergies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
