"""Updated: start/end datetime and timezone for events

Revision ID: 82b403455c40
Revises: 40c873a15712
Create Date: 2025-12-28 20:33:26.643986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b403455c40'
down_revision = '40c873a15712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('start', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.JSON(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
